<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="7" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-06T22:46:23 ICT" name="Default suite" finished-at="2024-04-06T22:46:23 ICT" duration-ms="493">
    <groups>
    </groups>
    <test started-at="2024-04-06T22:46:23 ICT" name="Default test" finished-at="2024-04-06T22:46:23 ICT" duration-ms="493">
      <class name="DAO.CaLamViecDaoTest">
        <test-method signature="getInstanceTest()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="getInstanceTest" finished-at="2024-04-06T22:46:23 ICT" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getInstanceTest -->
        <test-method signature="insertTest()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="insertTest" finished-at="2024-04-06T22:46:23 ICT" duration-ms="322" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Insert method should return 1 if successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Insert method should return 1 if successful
at DAO.CaLamViecDaoTest.insertTest(CaLamViecDaoTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertTest -->
        <test-method signature="selectAllTest()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="selectAllTest" finished-at="2024-04-06T22:46:23 ICT" duration-ms="40" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAllTest -->
        <test-method signature="selectByCondition1Test()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="selectByCondition1Test" finished-at="2024-04-06T22:46:23 ICT" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectByCondition1Test -->
        <test-method signature="selectByConditionTest()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="selectByConditionTest" finished-at="2024-04-06T22:46:23 ICT" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectByConditionTest -->
        <test-method signature="selectByIdTestCaLamViecModel()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="selectByIdTestCaLamViecModel" finished-at="2024-04-06T22:46:23 ICT" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectByIdTestCaLamViecModel -->
        <test-method signature="selectByIdTestString()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="selectByIdTestString" finished-at="2024-04-06T22:46:23 ICT" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectByIdTestString -->
        <test-method signature="updateTest()[pri:0, instance:DAO.CaLamViecDaoTest@7c711375]" started-at="2024-04-06T22:46:23 ICT" name="updateTest" finished-at="2024-04-06T22:46:23 ICT" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateTest -->
      </class> <!-- DAO.CaLamViecDaoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
